apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 104pvc
  name: 104pvc2b
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - image: nginx
    name: 104pvc3b
    ports:
     - containerPort: 80
    volumeMounts:
      - name: task-pv-storage
        mountPath: "/usr/share/nginx/html"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
