apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "118"
  name: "118"
spec:
  containers:
  - image: nginx
    name: "118"
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
