apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "131"
  name: "131"
spec:
  serviceAccountName: admin
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: "131"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
