apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "134"
  name: "134"
spec:
  containers:
  - image: nginx
    name: "134"
    ports:
    - containerPort: 80
    resources: {}
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
