apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "136"
  name: "136"
spec:
  containers:
  - image: nginx
    name: "136"
    resources: {}
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 25
      httpGet:
        path: /healthz
        port: 80
    readinessProbe:     
      initialDelaySeconds: 20
      periodSeconds: 25
      httpGet: 
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
