apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: "144"
    app: my-nginx
  name: "144"
spec:
  containers:
  - image: nginx
    name: "144"
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
