apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: 67dep
  name: 67dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 67dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: 67dep
    spec:
      containers:
      - image: nginx:1.17.1
        name: nginx
        ports:
        - containerPort: 80
        resources: {}

