apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: 90job
spec:
  parallelism: 3
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - command:
        - echo
        - Hello
        image: busybox
        name: 90job
        resources: {}
      restartPolicy: Never
status: {}
