apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-02-26T17:51:46Z"
  generation: 1
  labels:
    run: 55-dep
  name: 55-dep
  namespace: default
  resourceVersion: "64595"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/55-dep
  uid: acf302a4-3131-44e5-beba-9db2d7410ca3
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: 55-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: 55-dep
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: 55-dep
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2020-02-26T17:52:18Z"
    lastUpdateTime: "2020-02-26T17:52:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-02-26T17:51:46Z"
    lastUpdateTime: "2020-02-26T17:52:24Z"
    message: ReplicaSet "55-dep-5b9d6b4479" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
