apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test114
  name: test114
spec:
  containers:
  - image: nginx
    name: test114
    resources: {}
    env:
     -  name: ENVIRONMENT
        valueFrom:
          configMapKeyRef:
            name: env2
            key: var1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
